version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/app-dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=travel
    depends_on:
      db:
        condition: service_healthy

    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: travel
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p123456",
          "-e",
          "SELECT 1",
        ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
